# Generated by Django 5.2.8 on 2025-11-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('useProduct', models.CharField(choices=[('USED', 'USED'), ('AVAILABLE', 'AVAILABLE')], max_length=10)),
            ],
        ),
    ]
